import { svgHeader, svgFooter, rect, text, line, roundedRect, circle, sparkline } from './renderer.js';
import type { Theme } from '../types.js';
import type { RepoStats, Commit, LanguageStat, Author } from '../types.js';
import { getRelativeTime } from '../git/parser.js';
import { THEMES, langColor } from '../themes.js';

const MARGIN = 32;
const CARD_RADIUS = 16;

export interface CardSvgOptions {
  repoName: string;
  repoOwner: string;
  stats: RepoStats;
  recentCommits: Commit[];
  languages: LanguageStat[];
  authors: Author[];
  sparklineData: number[];
  theme: Theme;
  width?: number;
}

export function renderCard(opts: CardSvgOptions): string {
  const { repoName, repoOwner, stats, languages, authors, sparklineData, theme, width = 680 } = opts;
  const W = width;
  const W_INNER = W - MARGIN * 2;

  // Section heights
  const titleSectionH = 52;
  const statsSectionH = 72;
  const sparkSectionH = 56;
  const langSectionH = languages.length > 0 ? 36 + languages.slice(0, 5).length * 26 + 8 : 0;
  const contribSectionH = authors.length > 0 ? 56 : 0;
  const footerSectionH = 28;
  const totalH = MARGIN + titleSectionH + statsSectionH + sparkSectionH + langSectionH + contribSectionH + footerSectionH + MARGIN;

  let y = MARGIN;
  const titleY = y; y += titleSectionH;
  const statsY = y; y += statsSectionH;
  const sparkY = y; y += sparkSectionH;
  const langY = y; y += langSectionH;
  const contribY = y; y += contribSectionH;
  const footerY = y; y += footerSectionH;

  const svg = [
    svgHeader(W, totalH, theme),
    // Card background with outer margin
    roundedRect(MARGIN - 8, 8, W - MARGIN * 2 + 16, totalH - 16, CARD_RADIUS, {
      fill: theme.surface, stroke: theme.border, strokeWidth: 1,
    }),
    // ── Title ──────────────────────────────────────────
    text(MARGIN, titleY + 28, `${repoOwner} / ${repoName}`, {
      fontSize: 18, fontWeight: '700', fill: theme.text,
    }),
    text(MARGIN, titleY + 48, repoStatsOneLiner(stats), {
      fontSize: 11, fill: theme.textMuted,
    }),
    // ── Stats row ──────────────────────────────────────
    rect(MARGIN, statsY, W_INNER, statsSectionH - 12, { fill: theme.background, rx: 10 }),
    renderStatsRow(MARGIN + 20, statsY + 8, stats, theme),
    // ── Sparkline ───────────────────────────────────────
    text(MARGIN, sparkY + 14, 'Contribution Activity', { fontSize: 11, fontWeight: '600', fill: theme.textMuted }),
    sparkline(MARGIN, sparkY + 18, W_INNER, 28, sparklineData, theme),
    text(MARGIN, sparkY + sparkSectionH - 4, `${sparklineData.reduce((a, b) => a + b, 0)} commits in the last ${sparklineData.length} weeks`, {
      fontSize: 10, fill: theme.textMuted,
    }),
    // ── Language bars ────────────────────────────────────
    ...(languages.length > 0 ? [
      text(MARGIN, langY + 14, 'Languages', { fontSize: 11, fontWeight: '600', fill: theme.textMuted }),
      ...languages.slice(0, 5).map((lang, i) => {
        const ly = langY + 26 + i * 26;
        const barMaxW = W_INNER - 180;
        const barW = Math.max((lang.percentage / 100) * barMaxW, 2);
        const color = langColor(lang.name, theme);
        return [
          text(MARGIN, ly + 4, lang.name, { fontSize: 12, fill: theme.text }),
          text(W - MARGIN, ly + 4, `${lang.percentage.toFixed(1)}%`, { fontSize: 11, fill: theme.textMuted, textAnchor: 'end' }),
          rect(MARGIN, ly + 10, barMaxW, 8, { fill: theme.background, rx: 4 }),
          rect(MARGIN, ly + 10, barW, 8, { fill: color, rx: 4 }),
        ];
      }),
    ] : []),
    // ── Contributors ─────────────────────────────────────
    ...(authors.length > 0 ? [
      text(MARGIN, contribY + 14, 'Top Contributors', { fontSize: 11, fontWeight: '600', fill: theme.textMuted }),
      ...authors.slice(0, 3).map((a, i) => {
        const ax = MARGIN + i * (W_INNER / 3);
        const ay = contribY + 30;
        const color = [theme.accent, theme.accentAlt, theme.success][i] ?? theme.accent;
        const name = a.name.length > 18 ? a.name.substring(0, 16) + '…' : a.name;
        return [
          circle(ax + 10, ay + 8, 10, { fill: color }),
          text(ax + 28, ay + 6, name, { fontSize: 12, fill: theme.text }),
          text(ax + 28, ay + 20, `${a.commits} commits`, { fontSize: 10, fill: theme.textMuted }),
        ];
      }),
    ] : []),
    // ── Footer ──────────────────────────────────────────
    line(MARGIN, footerY, W - MARGIN, footerY, { stroke: theme.border }),
    text(W / 2, footerY + 18, 'Generated by termpeek', { fontSize: 9, fill: theme.textMuted, textAnchor: 'middle' }),
    svgFooter(),
  ];

  return svg.flat().join('\n');
}

function renderStatsRow(x: number, y: number, stats: RepoStats, theme: Theme): string {
  const items = [
    { icon: '⚡', value: `${stats.totalCommits}`, label: 'commits' },
    { icon: '📂', value: `${stats.totalBranches}`, label: 'branches' },
    { icon: '👥', value: `${stats.totalContributors}`, label: 'contributors' },
    { icon: '📅', value: stats.lastCommitDate ? getRelativeTime(stats.lastCommitDate) : 'N/A', label: 'last commit' },
  ];
  const itemW = 130;
  return items.map((item, i) => {
    const ix = x + i * itemW;
    return [
      text(ix, y + 18, `${item.icon} ${item.value}`, { fontSize: 18, fontWeight: '700', fill: theme.text }),
      text(ix, y + 34, item.label, { fontSize: 10, fill: theme.textMuted }),
    ].join('\n');
  }).join('\n');
}

function repoStatsOneLiner(stats: RepoStats): string {
  return `${stats.totalCommits} commits · ${stats.totalBranches} branches · ${stats.totalContributors} contributors · last activity ${stats.lastCommitDate ? getRelativeTime(stats.lastCommitDate) : 'N/A'}`;
}
