import { svgHeader, svgFooter, rect, text, line, roundedRect, circle, sparkline } from './renderer.js';
import type { Theme } from '../types.js';
import type { RepoStats, Commit, LanguageStat, Author } from '../types.js';
import { getRelativeTime } from '../git/parser.js';
import { THEMES, getTheme, langColor } from '../themes.js';

export interface CardSvgOptions {
  repoName: string;
  repoOwner: string;
  stats: RepoStats;
  recentCommits: Commit[];
  languages: LanguageStat[];
  authors: Author[];
  sparklineData: number[];
  theme: Theme;
  width?: number;
}

const ICON_FIRE = '🔥';
const ICON_BRANCH = '📂';
const ICON_USERS = '👥';
const ICON_CAL = '📅';
const ICON_COMMIT = '⚡';

export function renderCard(opts: CardSvgOptions): string {
  const { repoName, repoOwner, stats, recentCommits, languages, authors, sparklineData, theme, width = 620 } = opts;
  const CARD_RADIUS = 12;
  const PADDING = 24;
  const W = width;
  const innerWidth = W - PADDING * 2;

  // Calculate heights
  const titleH = 50;
  const statsH = 44;
  const sparklineH = 40;
  const langH = languages.length > 0 ? 20 + languages.slice(0, 5).length * 22 + 8 : 0;
  const contribH = authors.length > 0 ? 36 : 0;
  const footerH = 20;
  const cardH = titleH + statsH + sparklineH + langH + contribH + footerH + PADDING * 2;

  let y = 0;
  const titleY = y + PADDING;
  const statsY = titleY + titleH;
  const sparkY = statsY + statsH;
  const langY = sparkY + sparklineH;
  const contribY = langY + langH;
  const footerY = contribY + contribH + PADDING;

  const svg = [
    svgHeader(W, footerY + footerH + 4, theme),
    roundedRect(0, 0, W, footerY + footerH + 4, CARD_RADIUS, { fill: theme.surface, stroke: theme.border, strokeWidth: 1 }),
    // ── Title ──────────────────────────────────────────
    text(PADDING, titleY + 28, `${ICON_FIRE} ${repoOwner} / ${repoName}`, {
      fontSize: 16, fontWeight: '600', fill: theme.text,
    }),
    // ── Stats row ──────────────────────────────────────
    rect(PADDING, statsY, innerWidth, statsH, { fill: theme.background, rx: 8 }),
    renderStatBadge(ICON_COMMIT, `${stats.totalCommits}`, 'commits', PADDING + 10, statsY + 14, theme),
    renderStatBadge(ICON_BRANCH, `${stats.totalBranches}`, 'branches', PADDING + 130, statsY + 14, theme),
    renderStatBadge(ICON_USERS, `${stats.totalContributors}`, 'contributors', PADDING + 250, statsY + 14, theme),
    renderStatBadge(ICON_CAL, stats.lastCommitDate ? getRelativeTime(stats.lastCommitDate) : 'N/A', 'last commit', PADDING + 370, statsY + 14, theme),
    // ── Sparkline ───────────────────────────────────────
    sparkline(PADDING + 10, sparkY + 5, innerWidth - 20, 24, sparklineData, theme),
    // Commits label
    text(PADDING, sparkY + 36, `${sparklineData.reduce((a, b) => a + b, 0)} commits in last 14 weeks`, {
      fontSize: 10, fill: theme.textMuted,
    }),
    // ── Language bars ────────────────────────────────────
    ...(languages.length > 0 ? [
      text(PADDING, langY + 14, 'Languages', { fontSize: 11, fontWeight: '600', fill: theme.textMuted }),
      ...languages.slice(0, 5).map((lang, i) => {
        const ly = langY + 22 + i * 22;
        const barW = innerWidth * (lang.percentage / 100);
        const color = langColor(lang.name, theme);
        return [
          text(PADDING, ly + 10, lang.name, { fontSize: 11, fill: theme.text }),
          rect(PADDING + 90, ly + 1, innerWidth - 90 - 70, 11, { fill: theme.background, rx: 5 }),
          rect(PADDING + 90, ly + 1, barW, 11, { fill: color, rx: 5 }),
          text(PADDING + 90 + innerWidth - 70, ly + 10, `${lang.percentage.toFixed(1)}%`, { fontSize: 10, fill: theme.textMuted }),
        ];
      }),
    ] : []),
    // ── Contributors ─────────────────────────────────────
    ...(authors.length > 0 ? [
      text(PADDING, contribY + 14, 'Top Contributors', { fontSize: 11, fontWeight: '600', fill: theme.textMuted }),
      ...authors.slice(0, 3).map((a, i) => {
        const ax = PADDING + i * 160;
        const ay = contribY + 24;
        return [
          circle(ax + 10, ay + 8, 10, { fill: [theme.accent, theme.accentAlt, theme.success][i] ?? theme.accent }),
          text(ax + 28, ay + 12, a.name, { fontSize: 11, fill: theme.text }),
          text(ax + 28, ay + 24, `${a.commits} commits`, { fontSize: 9, fill: theme.textMuted }),
        ];
      }),
    ] : []),
    // ── Footer ──────────────────────────────────────────
    line(0, footerY, W, footerY, { stroke: theme.border, strokeWidth: 1 }),
    text(W / 2, footerY + 14, 'Generated by termpeek', { fontSize: 9, fill: theme.textMuted, textAnchor: 'middle' }),
    svgFooter(),
  ];

  return svg.flat().join('\n');
}

function renderStatBadge(icon: string, value: string, label: string, x: number, y: number, theme: Theme): string {
  return [
    text(x, y, `${icon} ${value}`, { fontSize: 14, fontWeight: '600', fill: theme.text }),
    text(x, y + 16, label, { fontSize: 10, fill: theme.textMuted }),
  ].join('\n');
}
